BookTime/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from main import admin
from main import views

urlpatterns = [
    path("admin/", admin.main_admin.urls),
    path("office-admin/", admin.central_office_admin.urls),
    path("dispatch-admin/", admin.dispatchers_admin.urls),
    path("", include("main.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("order-dashboard/", views.OrderView.as_view(), name="order_dashboard"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

main/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework import routers

from main import forms, api
from . import views

router = routers.DefaultRouter()
router.register(r"orderlines", api.PaidOrderLineViewSet)
router.register(r"orders", api.PaidOrderViewSet)

urlpatterns = [
    path(
        "about-us/",
        TemplateView.as_view(template_name="about_us.html"),
        name="about_us",
    ),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("contact-us/", views.ContactUsView.as_view(), name="contact_us"),
    path("products/<slug:tag>/", views.ProductListView.as_view(), name="products-list"),
    path(
        "product/<slug:slug>/",
        # DetailView.as_view(model=models.Product),
        views.ProductDetailView.as_view(),
        name="product",
    ),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="login.html", form_class=forms.AuthenticationForm
        ),
        name="login",
    ),
    path("address/", views.AddressListView.as_view(), name="address_list"),
    path("address/create/", views.AddressCreateView.as_view(), name="address_create"),
    path("address/<int:pk>/", views.AddressUpdateView.as_view(), name="address_update"),
    path(
        "address/<int:pk>/delete/",
        views.AddressDeleteView.as_view(),
        name="address_delete",
    ),
    path("add_to_cart/", views.add_to_cart, name="add_to_cart"),
    path("cart/", views.manage_cart, name="cart"),
    path(
        "order/done/",
        TemplateView.as_view(template_name="order_done.html"),
        name="checkout_done",
    ),
    path(
        "order/address_select/",
        views.AddressSelectionView.as_view(),
        name="address_select",
    ),
    path("api/", include(router.urls)),
    path("customer-service/<int:order_id>/", views.room, name="cs_chat"),
]

main/models.py
import logging

from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

from main.managers import ActiveManager, ProductTagManager, UserManager

logger = logging.getLogger(__name__)


class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides self-
    updating ``created`` and ``modified`` fields.
    """

    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class User(AbstractUser):
    username = None
    email = models.EmailField("email address", unique=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
    objects = UserManager()

    @property
    def is_employee(self):
        return self.is_active and (
            self.is_superuser
            or self.is_staff
            and self.groups.filter(name="Employees").exists()
        )

    @property
    def is_dispatcher(self):
        return self.is_active and (
            self.is_superuser
            or self.is_staff
            and self.groups.filter(name="Dispatchers").exists()
        )


class ProductTag(TimeStampedModel):
    """Product Tag Model"""

    name = models.CharField(max_length=32)
    slug = models.SlugField(max_length=48)
    description = models.TextField(blank=True)
    active = models.BooleanField(default=True)

    objects = ProductTagManager()

    def __str__(self):
        return self.name

    def natural_key(self):
        return self.slug

    class Meta:
        verbose_name = _("Product Tag")
        verbose_name_plural = _("Product Tags")


class Product(TimeStampedModel):
    """Product Model"""

    name = models.CharField(max_length=32)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    tags = models.ManyToManyField(to=ProductTag, blank=True)
    slug = models.SlugField(max_length=48)
    active = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)

    objects = ActiveManager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Product")
        verbose_name_plural = _("Products")


class ProductImage(TimeStampedModel):
    """Product Image Model"""

    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="product-images")
    thumbnail = models.ImageField(upload_to="product-thumbnails", null=True)

    def __str__(self):
        return f"{self.product.id} + | + {self.product.name}"

    class Meta:
        verbose_name = _("Product Image")
        verbose_name_plural = _("Product Images")


class Address(TimeStampedModel):
    SUPPORTED_COUNTRIES = (
        ("in", "India"),
        ("en", "England"),
        ("us", "United States of America"),
    )
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    name = models.CharField(max_length=60)
    address1 = models.CharField(verbose_name=_("Address Line 1"), max_length=60)
    address2 = models.CharField(
        verbose_name=_("Address Line 2"), max_length=60, blank=True
    )
    pin_code = models.CharField(verbose_name=_("ZIP / Postal Code"), max_length=12)
    city = models.CharField(max_length=60)
    country = models.CharField(max_length=3, choices=SUPPORTED_COUNTRIES)

    def __str__(self):
        return ", ".join(
            [
                self.name,
                self.address1,
                self.address2,
                self.pin_code,
                self.city,
                self.country,
            ]
        )


class Cart(TimeStampedModel):
    OPEN = 10
    SUBMITTED = 20
    STATUSES = ((OPEN, "Open"), (SUBMITTED, "Submitted"))

    user = models.ForeignKey(to=User, on_delete=models.CASCADE, blank=True, null=True)
    status = models.IntegerField(choices=STATUSES, default=OPEN)

    def is_empty(self):
        return self.productincart_set.all().count() == 0

    def count(self):
        return sum(i.quantity for i in self.productincart_set.all())

    def create_order(self, billing_address, shipping_address):
        if not self.user:
            raise ValidationError("Cannot create order without user")

        logger.info(
            "Creating Order for basket_id=%d"
            ", shipping_address_id=%d, billing_address_id=%d",
            self.id,
            shipping_address.id,
            billing_address.id,
        )
        order_data = {
            "user": self.user,
            "billing_name": billing_address.name,
            "billing_address1": billing_address.address1,
            "billing_address2": billing_address.address2,
            "billing_pin_code": billing_address.pin_code,
            "billing_city": billing_address.city,
            "billing_country": billing_address.country,
            "shipping_name": shipping_address.name,
            "shipping_address1": shipping_address.address1,
            "shipping_address2": shipping_address.address2,
            "shipping_pin_code": shipping_address.pin_code,
            "shipping_city": shipping_address.city,
            "shipping_country": shipping_address.country,
        }
        order = Order.objects.create(**order_data)
        c = 0
        for product in self.productincart_set.all():
            for item in range(product.quantity):
                order_line_data = {"order": order, "product": product.product}
                order_line = OrderLine.objects.create(**order_line_data)
                c += 1
            logger.info("Created order with id=%d and lines_count=%d", order.id, c)
        self.status = Cart.SUBMITTED
        self.save()
        return order

    def __str__(self):
        return f"{self.user.first_name}'s Cart"


class ProductInCart(TimeStampedModel):
    cart = models.ForeignKey(to=Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])


class Order(TimeStampedModel):
    """Order Model"""

    NEW = 10
    PAID = 20
    DONE = 30
    STATUSES = ((NEW, "New"), (PAID, "Paid"), (DONE, "Done"))

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.IntegerField(choices=STATUSES, default=NEW)
    billing_name = models.CharField(max_length=60)
    billing_address1 = models.CharField(max_length=60)
    billing_address2 = models.CharField(max_length=60, blank=True)
    billing_pin_code = models.CharField(max_length=12)
    billing_city = models.CharField(max_length=60)
    billing_country = models.CharField(max_length=3)
    shipping_name = models.CharField(max_length=60)
    shipping_address1 = models.CharField(max_length=60)
    shipping_address2 = models.CharField(max_length=60, blank=True)
    shipping_pin_code = models.CharField(max_length=12)
    shipping_city = models.CharField(max_length=60)
    shipping_country = models.CharField(max_length=3)

    last_spoken_to = models.ForeignKey(
        User, null=True, related_name="cs_chats", on_delete=models.SET_NULL
    )

    def __str__(self):
        return f"{self.user.first_name}'s Order"


class OrderLine(TimeStampedModel):
    """Order Line Model"""

    NEW = 10
    PROCESSING = 20
    SENT = 30
    CANCELLED = 40
    STATUSES = (
        (NEW, "New"),
        (PROCESSING, "Processing"),
        (SENT, "Sent"),
        (CANCELLED, "Cancelled"),
    )

    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="lines")
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    status = models.IntegerField(choices=STATUSES, default=NEW)

main/forms.py
from django import forms
from django.core.mail import send_mail
import logging
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm as DjangoUserCreationForm
from django.contrib.auth.forms import UsernameField
from django.forms import inlineformset_factory

from . import models, widgets
from .models import Cart, ProductInCart

logger = logging.getLogger(__name__)


class ContactForm(forms.Form):
    name = forms.CharField(label="Your Name", max_length=100)
    message = forms.CharField(max_length=600, widget=forms.Textarea)

    def send_mail(self):
        logger.info("Sending email to customer service")
        message = "From: {0}\n{1}".format(
            self.cleaned_data["name"], self.cleaned_data["message"]
        )
        send_mail(
            "Site message",
            message,
            "site@intensivegalaxy.domain",
            ["customerservice@intensivegalaxy.domain"],
            fail_silently=False,
        )


class UserCreationForm(DjangoUserCreationForm):
    class Meta(DjangoUserCreationForm.Meta):
        model = models.User
        fields = ("email",)
        field_classes = {"email": UsernameField}

    def send_mail(self):
        logger.info("Sending signup email for email=%s", self.cleaned_data["email"])
        message = "Welcome {}".format(self.cleaned_data["email"])
        send_mail(
            "Welcome to Intensive Galaxy",
            message,
            "site@intensive_galaxy.domain",
            [self.cleaned_data["email"]],
            fail_silently=True,
        )


class AuthenticationForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(strip=False, widget=forms.PasswordInput)

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user = None
        super().__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if email is not None and password:
            self.user = authenticate(self.request, email=email, password=password)
            if self.user is None:
                raise forms.ValidationError("Invalid email/password combination.")
            logger.info("Authentication successful for email=%s", email)
        return self.cleaned_data

    def get_user(self):
        return self.user


CartLineFormSet = inlineformset_factory(
    Cart,
    ProductInCart,
    fields=("quantity",),
    extra=0,
    widgets={"quantity": widgets.PlusMinusNumberInput()},
)


class AddressSelectionForm(forms.Form):
    billing_address = forms.ModelChoiceField(queryset=None)
    shipping_address = forms.ModelChoiceField(queryset=None)

    def __init__(self, user, *args, **kwargs):
        super(AddressSelectionForm, self).__init__(*args, **kwargs)
        queryset = models.Address.objects.filter(user=user)
        self.fields["billing_address"].queryset = queryset
        self.fields["shipping_address"].queryset = queryset

main/templates/address_list.html
{% extends "base.html" %}
{% block content %}
    <h1>List of your addresses:</h1>
    {% for address in object_list %}
        <p>
            {{ address.name }}<br>
            {{ address.address1 }}<br>
            {{ address.address2 }}<br>
            {{ address.city }}<br>
            {{ address.get_country_display }}<br>
        </p>
        <p>
            <a href="{% url "address_update" address.id %}">Update address</a>
        </p>
        <p>
            <a href="{% url "address_delete" address.id %}">Delete address</a>
        </p>
        {% if not forloop.last %}
            <hr>
        {% endif %}
    {% endfor %}
    <p>
        <a href="{% url "address_create" %}">Add new address</a>
    </p>
{% endblock content %}

main/templates/address_update.html
{% extends "base.html" %}
{% block content %}
    <h2>Add a new address</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-­primary">Submit</button>
    </form>
{% endblock content %}

main/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-­fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <title>Intensive Galaxy</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-­light">
    <a class="navbar-brand" href="/">Intensive Galaxy</a>
    <button
            class="navbar-toggler" type="button"
            data-toggle="collapse"
            data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if request.path == "/" %}active{% endif %}">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item {% if request.path == "/signup/" %}active{% endif %}">
                <a class="nav-link" href="/signup/">Register</a>
            </li>
            <li class="nav-item {% if request.path == "/login/" %}active{% endif %}">
                <a class="nav-link" href="/login/">Login</a>
            </li>
            <li class="nav-item {% if request.path == "/products/all/" %}active{% endif %}">
                <a class="nav-link" href="/products/all/">Products</a>
            </li>
            <li class="nav-item {% if request.path == "/about-us/" %}active
            {% endif %}">
                <a class="nav-link" href="/about-us/">About Us</a>
            </li>
            <li class="nav-item {% if request.path == "/contact-us/" %}active
            {% endif %}">
                <a class="nav-link" href="/contact-us/">Contact Us</a>
            </li>
        </ul>
    </div>
</nav>

{% for message in messages %}
    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
{% endfor %}

{% if request.basket %}
    <div>
        {{ request.basket.count }}
        items in basket
    </div>
{% endif %}

{% block content %}
{% endblock content %}
<script src="{% static "js/jquery.min.js" %}"></script>
<script src="{% static "js/popper.min.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>

{% block js %}
{% endblock js %}
</body>
</html>

main/templates/cart.html
{% extends "base.html" %}
{% block content %}
  <h2>Cart</h2>
  {% if formset %}
    <p>You can adjust the quantities below.</p>
    <form method="POST">
      {% csrf_token %}
      {{ formset.management_form }}
      {% for form in formset %}
        <p>
          {{ form.instance.product.name }}
          {{ form }}
        </p>
      {% endfor %}
      <button type="submit" class="btn btn-default">Update cart</button>
    {% if user.is_authenticated %}
        <a href="{% url "address_select" %}" class="btn btn-primary">Please Order</a>
    {% else %}
        <a href="{% url "signup" %}?next={% url "address_select" %}" class="btn btn-primary">SignUp</a>
        <a href="{% url "login" %}?next={% url "address_select" %}" class="btn btn-primary">Login</a>
    {% endif %}
    </form>
  {% else %}
    <p>You have no items in the cart.</p>
  {% endif %}
{% endblock content %}

{% block js %}
  {% if formset %}
    {{ formset.media }}
  {% endif %}
{% endblock js %}

main/templates/chat_room.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
    <script
            src="{% static "js/reconnecting-websocket.min.js" %}" charset="utf-8"></script>
</head>
<body>
<textarea id="chat-log" cols="100" rows="20"></textarea><br/>
<input id="chat-message-input" type="text" size="100"/><br/>
<input id="chat-message-submit" type="button" value="Send"/>
</body>
<script>
    var roomName = {{ room_name_json }};
    var chatSocket = new ReconnectingWebSocket(
        'ws://' + window.location.host + '/ws/customer-service/' +
        roomName + '/'
    );
    chatSocket.onmessage = function (e) {
        var data = JSON.parse(e.data);
        var username = data['username'];
        if (data['type'] == "chat_join") {
            message = (username + ' joined\n ');
        } else if (data['type'] == "chat_leave") {
            message = (username + ' left\n ');
        } else {
            message = (username + ': ' + data['message'] + '\n');
        }
        document
            .querySelector('#chat-log')
            .value += message;
    };
    chatSocket.onclose = function (e) {
        console.error('Chat socket closed unexpectedly');
    };
    document
        .querySelector('#chat-message-input')
        .focus();
    document
        .querySelector('#chat-message-input')
        .onkeyup = function (e) {
        if (e.keyCode === 13) { // enter, return
            document
                .querySelector('#chat-message-submit')
                .click();
        }
    };
    document
        .querySelector('#chat-message-submit')
        .onclick = function (e) {
        var messageInputDom = document.querySelector(
            '#chat-message-input'
        );
        var message = messageInputDom.value;
        chatSocket.send(
            JSON.stringify({'type': 'message', 'message': message})
        );
        messageInputDom.value = '';
    };
    setInterval(function () {
        chatSocket.send(JSON.stringify({'type': 'heartbeat'}));
    }, 10000);
</script>
</html>

main/templates/contact_form.html
{% extends "base.html" %}

{% block content %}
    <h2>Contact us</h2>
    <p>Please fill the form below to contact us</p>
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{ form.name.label_tag }}
            <input type="text" class="form-control {% if form.name.errors %}is-invalid{% endif %}"
                   id="id_name"
                   name="name"
                   placeholder="Your name"
                   value="{{ form.name.value|default:"" }}">
            {% if form.name.errors %}
                <div class="invalid-feedback">
                    {{ form.name.errors }}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.message.label_tag }}
            <textarea class="form-control {% if form.message.errors %} is-­invalid {% endif %}"
                      id="id_message"
                      name="message"
                      rows="3">
          {{ form.message.value|default:"" }}
        </textarea>
            {% if form.message.errors %}
                <div class="invalid-feedback">
                    {{ form.message.errors }}
                </div>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock content %}

main/templates/home.html
{% extends "base.html" %}

{% block content %}
    <h2>Home</h2>
    <p>This will be the content of home</p>
{% endblock content %}

main/templates/login.html
{% extends "base.html" %}
{% block content %}
    <h2>Login</h2>
    <p>Please fill the form below.</p>
    <form method="POST">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% include "includes/field.html" with field=form.email %}
        {% include "includes/field.html" with field=form.password %}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock content %}

main/templates/most_bought_products.html
{% extends "admin/base_site.html" %}
{% block extrahead %}
    <script
            src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js"
            integrity="sha256-XF29CBwU1MWLaGEnsELogU6Y6rcc5nCkhhx89nFMIDQ=" crossorigin="anonymous"></script>
{% endblock extrahead %}
{% block content %}
    <p>
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Set period"/>
    </form>
    </p>
    {% if labels and values %}
        <canvas id="myChart" width="900" height="400"></canvas>
        <script>
            var ctx = document.getElementById("myChart");
            var myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: {{ labels|safe }},
                    datasets: [
                        {
                            label: 'No of purchases',
                            backgroundColor: 'blue',
                            data: {{ values|safe }}
                        }
                    ]
                },
                options: {
                    responsive: false,
                    scales: {
                        yAxes: [
                            {
                                ticks: {
                                    beginAtZero: true
                                }
                            }
                        ]
                    }
                }
            });
        </script>
    {% endif %}
{% endblock %}

main/templates/order_done.html
{% extends "base.html" %}
{% block content %}
  <p>Thanks for your order.</p>
{% endblock content %}

main/templates/order_filter.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}
{% block content %}
    <h2>Order dashboard</h2>
    <form method="get">
        {{ filter.form.as_p }}
        <input type="submit"/>
    </form>
    <p>
        {% render_table filter.qs %}
    </p>
{% endblock content %}

main/templates/orders_per_day.html
{% extends "admin/base_site.html" %}
{% block extrahead %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js" integrity="sha256-XF29CBwU1MWLaGEnsELogU6Y6rcc5nCkhhx89nFMIDQ="crossorigin="anonymous"></script>
{% endblock extrahead %}
{% block content %}
    <canvas id="myChart" width="900" height="400"></canvas>
    <script>
        var ctx = document.getElementById("myChart");
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: {{ labels|safe }},
                datasets: [
                    {
                        label: 'No of orders',
                        backgroundColor: 'blue',
                        data: {{ values|safe }}
                    }
                ]
            },
            options: {
                responsive: false,
                scales: {
                    yAxes: [
                        {
                            ticks: {
                                beginAtZero: true
                            }
                        }
                    ]
                }
            }
        });
    </script>
{% endblock %}

main/templates/product_list.html
{% extends "base.html" %}
{% block content %}
    <h1>products</h1>
    {% for product in page_obj %}
        <p>{{ product.name }}</p>
        <p>
            <a href="{% url "product" product.slug %}">See it here</a>
        </p>
        {% if not forloop.last %}
            <hr>
        {% endif %}
    {% endfor %}
    <nav>
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Previous</a>
                </li>
            {% endif %}
            {% for pagenum in page_obj.paginator.page_range %}
                <li class="page-item{% if page_obj.number == pagenum %}active{% endif %}">
                    <a class="page-link" href="?page={{ pagenum }}">{{ pagenum }}</a>
                </li>
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Next</a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endblock content %}

main/templates/signup.html
{% extends "base.html" %}

{% block content %}
    <h2>Sign up</h2>
    <p>Please fill the form below.</p>
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{ form.email.label_tag }}
            <input type="email" class="form-control {% if form.email.errors %}is-­invalid{% endif %}"
                    id="id_email"
                    name="email"
                    placeholder="Your email"
                    value="{{ form.email.value|default:"" }}"/>
            {% if form.email.errors %}
                <div class="invalid-feedback">
                    {{ form.email.errors }}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.password1.label_tag }}
            <input type="password" class="form-control {% if form.password1.errors %}is-­invalid{% endif %}"
                    id="id_password1"
                    name="password1"
                    value="{{ form.password1.value|default:"" }}"/>
            {% if form.password1.errors %}
                <div class="invalid-feedback">
                    {{ form.password1.errors }}
                </div>
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.password2.label_tag }}
            <input type="password" class="form-control{% if form.password2.errors %}is-­invalid{% endif %}"
                    id="id_password2"
                    name="password2"
                    value="{{ form.password2.value|default:"" }}"/>
            {% if form.password2.errors %}
                <div class="invalid-feedback">
                    {{ form.password2.errors }}
                </div>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock content %}